export default {
  version: "0.1.1",
  createdAt: "2026-09-25T13:34:38.652Z",
  layout: {
    preset: "standard",
  },
  database: "none",
  orm: "none",
  backend: "hono",
  runtime: "bun",
  frontend: ["tanstack-router"],
  addons: ["turborepo"],
  examples: [],
  testing: [],
  auth: "none",
  payments: [],
  observability: ["getmonitor"],
  communication: "none",
  packageManager: "bun",
  dbSetup: "none",
  api: "trpc",
  webDeploy: "none",
  serverDeploy: "none",
};
