export const enUS = {
  meta: {
    title: "kubojs — create type-safe TypeScript projects",
    description:
      "Modern CLI to scaffold end-to-end TypeScript projects with type safety, best practices, and customizable configuration",
    keywords: [
      "TypeScript",
      "project scaffolding",
      "boilerplate",
      "type safety",
      "create projects",
      "Drizzle",
      "Prisma",
      "hono",
      "elysia",
      "turborepo",
      "trpc",
      "orpc",
      "turso",
      "neon",
      "Better-Auth",
      "convex",
      "monorepo",
      "CLI",
      "kubojs",
    ],
    authors: "kubojs team",
    ogAlt: "kubojs — CLI for type-safe TypeScript projects",
    openGraphLocale: "en_US",
    category: "Technology",
  },
  fumadocs: {
    search: "Search",
    searchNoResult: "No results found",
    toc: "On this page",
    tocNoHeadings: "No headings",
    lastUpdate: "Last updated on",
    chooseLanguage: "Choose language",
    nextPage: "Next page",
    previousPage: "Previous page",
    editOnGithub: "Edit on GitHub",
  },
  header: {
    homeAria: "Kubo home",
    mainNavAria: "Main navigation",
    docs: "Docs",
    socialX: "Kubo on X",
    socialGitHub: "Kubo on GitHub",
    buildStack: "Build stack",
  },
  nav: {
    docs: "Docs",
    builder: "Builder",
    analytics: "Analytics",
    demo: "Demo",
  },
  hero: {
    sectionAria: "Main section",
    titleLine1: "Build without",
    titleLine2: "starting from scratch.",
    titleFull: "Build without starting from scratch.",
    body: "Pick the right tools for your idea and start building without starting from scratch. Clean, precise, and your way.",
    copyAria: "Copy command: {command}",
    copiedAria: "Command copied",
    copyTitle: "Click to copy",
    copiedTitle: "Copied",
    copySr: "Copy command",
    copiedSr: "Command copied",
    starAria: "Open the Kubo repository on GitHub to star it",
    starTitle: "Star on GitHub",
  },
  panels: {
    features: ["FRONTEND + BACKEND", "DATABASE SETUP", "AUTH AND PAYMENTS", "PRODUCTION-READY"],
    documentation: {
      title: "Build with Kubo.",
      description:
        "Browse practical guides to understand each layer, configure your project, and ship to production.",
      cta: "Read the docs",
      imageAlt: "Example code generated by Kubo",
    },
    integrations: {
      title: "Build your stack",
      description:
        "Choose every layer and generate a TypeScript base ready to grow with your project.",
      cta: "Build your stack",
      imageAlt: "Brazilian integrations available in the Kubo Stack Builder",
    },
    stackBuilder: {
      title: "Explore integrations",
      descriptionBefore: "Build with the best tools and discover the edge of ",
      descriptionHighlight: "Brazilian integrations",
      descriptionAfter: ".",
      cta: "Explore integrations",
      imageAlt: "Kubo Stack Builder interface",
    },
  },
  finalCta: {
    titleLine1: "Stop assembling.",
    titleLine2: "Start shipping.",
    buildStack: "Build your stack",
  },
  footer: {
    navAria: "Footer navigation",
    newsletter: "Newsletter",
    emailLabel: "Your email",
    emailPlaceholder: "you@example.com",
    subscribe: "Join",
    groups: {
      create: "Create",
      explore: "Explore",
      community: "Community",
    },
    links: {
      builder: "Builder",
      docs: "Docs",
      npm: "NPM package",
      discord: "Discord",
      github: "GitHub",
    },
  },
  community: {
    sectionAria: "Community",
    storiesAria: "Community stories",
    videoDescription: "Watch a community member ship a TypeScript stack.",
    noteTitle: "Community dispatch {n}.",
    noteDescription: "See the stack, context, and implementation notes.",
  },
} as const;

type LocalizedDictionary<T> = T extends string
  ? string
  : T extends readonly unknown[]
    ? { readonly [Key in keyof T]: LocalizedDictionary<T[Key]> }
    : T extends object
      ? { readonly [Key in keyof T]: LocalizedDictionary<T[Key]> }
      : T;

export type Dictionary = LocalizedDictionary<typeof enUS>;
